---
- name: Create Wordpress database
  mysql_db:
    name: wordpress
    state: present

- name: Create Wordpress user for database
  mysql_user:
    name: wordpress
    password: "P@ssw0rd"
    priv: "wordpress.*:ALL"
    state: present

- name: Install Wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html
    copy: no
    owner: www-data
    group: www-data
