---
- name: Create Wordpress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present

- name: Create Wordpress user for database
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_pass }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present

- name: Install Wordpress
  unarchive:
    src: "{{ wordpress_download_url }}"
    dest: "{{ wordpress_install_path }}"
    copy: no
    owner: "{{ wordpress_owner_user }}"
    group: "{{ wordpress_owner_group }}"

- name: Copy Wordpress configuration
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_install_path }}/wordpress/wp-config.php"
    owner: "{{ wordpress_owner_user }}"
    group: "{{ wordpress_owner_group }}"
    mode: 0644
