---
- name: Update packages cache
  apt:
    update_cache: yes

- name: Install MySQL Server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb
    - mysql-server

- name: Create database
  mysql_db:
    name: wordpress
    state: present

- name: Create wordpress user for database
  mysql_user:
    name: wordpress
    password: "P@ssw0rd"
    priv: "wordpress.*:ALL"
    state: present

- name: Install PHP5 + Apache
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-mysql

- name: Restart Apache2
  service:
    name: apache2
    state: restarted

- name: Install Wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html
    copy: no
    owner: www-data
    group: www-data
