---
- name: Update packages cache
  apt:
    update_cache: yes

- name: Install PHP5 + Apache
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-mysql
  notify: Restart Apache2
